
-- Script generated by SimpleSpy - credits to exx#9394

local args = {
    [1] = {
        [1] = "QuestTalkStart"
    }
}

game:GetService("ReplicatedStorage").RemoteEvent:FireServer(unpack(args))

this script ^^^ is when you talk to the quest npc


-- Script generated by SimpleSpy - credits to exx#9394

local args = {
    [1] = {
        [1] = "Update_Flying_Status",
        [2] = false
    }
}

game:GetService("ReplicatedStorage").RemoteEvent:FireServer(unpack(args))

this code ^^^ is always fireing checking if a player is flying or not, maybe useful for flying before player has the ability

this code sends a fist strength activation request works while not holding the fist icon
    
    -- Script generated by SimpleSpy - credits to exx#9394

local args = {
    [1] = {
        [1] = "Add_FS_Request"
    }
}

game:GetService("ReplicatedStorage").RemoteEvent:FireServer(unpack(args))



